### ISSUE TITLE
Build for 1.37.27?

### ISSUE THREAD

**Issue by ndarilek** [koute/emscripten-build#1]
I know you just pushed 1.37.26. Thanks for that, as it included a fix I needed. Unfortunately, I recently hit [this issue](https://github.com/kripken/emscripten/issues/5940), which was resolved in emsdk incoming a few days ago, before 1.37.27 I assume. I can use my emsdk install in the meantime, but this automated download is significantly smaller and much more convenient.

Thanks! I won't ask for upgrades at each new Emscripten release, but my app fails on .26 and works on .27 with no local changes, so I assume the previously-linked fix is probably worth shipping.

**Comment by koute** [comment]
No problem! I'll update it sometime tommorow.

**Comment by ndarilek** [comment]
Thanks!

**Comment by koute** [comment]
Done!

**Comment by ndarilek** [comment]
Thanks, confirming that my SDL issue is now resolved locally. I 
appreciate it!
